site_name: DAP Mode

nav:
  - Home: README.md
  - How to: page/how-to.md
  - Tutorials:
      - Clojure: page/clojure.md
  - Changelog: CHANGELOG.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: screenshots/logo.png
  favicon: screenshots/logo.png
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/dap-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/emacs-lsp/lsp-mode

repo_name: emacs-lsp/dap-mode
repo_url: https://github.com/emacs-lsp/dap-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: '#'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
