name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: README.org -> README.md
        uses: docker://pandoc/core:2.9
        with:
          args: -s README.org -t gfm -o docs/README.md

      - name: CHANGELOG.org -> CHANGELOG.md
        uses: docker://pandoc/core:2.9
        with:
          args: -s CHANGELOG.org -t gfm -o docs/CHANGELOG.md

      - name: MkDocs
        run: |
          cp -rf screenshots docs

          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v ${PWD}:/docs docker.pkg.github.com/emacs-lsp/docs-image/docs-image -- build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
